repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [markdown]
    -   id: check-yaml
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ["--max-line-length=180", "--ignore=D100,F403,F405,E722,D103,D104,D400"]